# Generated by Django 4.2.4 on 2026-09-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='movie',
        ),
        migrations.AddField(
            model_name='report',
            name='review',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.review'),
            preserve_default=False,
        ),
    ]
