# Generated by Django 4.2.4 on 2026-09-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_report_comment_remove_report_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
