# Generated by Django 5.0 on 2026-09-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_review_is_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
